In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('main_data_source/diabetes_dataset.csv')
data

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,Female,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,Male,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,Female,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,Male,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,Male,Other,Graduate,Upper-Middle,Unemployed,Former,1,136,8.3,...,45,150,116,113,109,14.58,5.55,26.0,Pre-Diabetes,0
99996,41,Female,White,Graduate,Middle,Employed,Never,3,76,8.8,...,55,123,146,96,146,9.02,5.97,24.4,Pre-Diabetes,0
99997,57,Female,Black,No formal,Upper-Middle,Employed,Former,4,121,9.9,...,50,111,184,93,132,2.57,5.21,27.6,No Diabetes,0
99998,47,Female,Black,Highschool,Lower-Middle,Retired,Never,3,52,5.9,...,68,91,116,106,117,9.81,5.53,26.4,Pre-Diabetes,0
99999,52,Female,White,Postgraduate,Middle,Employed,Never,1,248,2.7,...,31,183,87,91,142,15.93,5.73,27.9,Pre-Diabetes,0

In [4]:
data['gender'] = data['gender'].map({'Male': 0, 'Female': 1})
data

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,0.0,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1
1,48,1.0,White,Highschool,Middle,Employed,Former,1,143,6.7,...,55,50,30,93,150,2.00,5.63,23.0,No Diabetes,0
2,60,0.0,Hispanic,Highschool,Middle,Unemployed,Never,1,57,6.4,...,66,99,36,118,195,5.07,7.51,44.7,Type 2,1
3,74,1.0,Black,Highschool,Low,Retired,Never,0,49,3.4,...,50,79,140,139,253,5.28,9.03,38.2,Type 2,1
4,46,0.0,White,Graduate,Middle,Retired,Never,1,109,7.2,...,52,125,160,137,184,12.74,7.20,23.5,Type 2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,Other,Graduate,Upper-Middle,Unemployed,Former,1,136,8.3,...,45,150,116,113,109,14.58,5.55,26.0,Pre-Diabetes,0
99996,41,1.0,White,Graduate,Middle,Employed,Never,3,76,8.8,...,55,123,146,96,146,9.02,5.97,24.4,Pre-Diabetes,0
99997,57,1.0,Black,No formal,Upper-Middle,Employed,Former,4,121,9.9,...,50,111,184,93,132,2.57,5.21,27.6,No Diabetes,0
99998,47,1.0,Black,Highschool,Lower-Middle,Retired,Never,3,52,5.9,...,68,91,116,106,117,9.81,5.53,26.4,Pre-Diabetes,0
99999,52,1.0,White,Postgraduate,Middle,Employed,Never,1,248,2.7,...,31,183,87,91,142,15.93,5.73,27.9,Pre-Diabetes,0

In [5]:
data['ethnicity'].value_counts()

ethnicity
White       44997
Hispanic    20103
Black       17986
Asian       11865
Other        5049
Name: count, dtype: int64

In [6]:
ethnicity_dummies = pd.get_dummies(data['ethnicity'], prefix='ethnicity').astype(int)
data = pd.concat([data, ethnicity_dummies], axis=1)
data = data.drop(columns='ethnicity')
data

,age,gender,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,...,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes,ethnicity_Asian,ethnicity_Black,ethnicity_Hispanic,ethnicity_Other,ethnicity_White
0,58,0.0,Highschool,Lower-Middle,Employed,Never,0,215,5.7,7.9,...,6.36,8.18,29.6,Type 2,1,1,0,0,0,0
1,48,1.0,Highschool,Middle,Employed,Former,1,143,6.7,6.5,...,2.00,5.63,23.0,No Diabetes,0,0,0,0,0,1
2,60,0.0,Highschool,Middle,Unemployed,Never,1,57,6.4,10.0,...,5.07,7.51,44.7,Type 2,1,0,0,1,0,0
3,74,1.0,Highschool,Low,Retired,Never,0,49,3.4,6.6,...,5.28,9.03,38.2,Type 2,1,0,1,0,0,0
4,46,0.0,Graduate,Middle,Retired,Never,1,109,7.2,7.4,...,12.74,7.20,23.5,Type 2,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,Graduate,Upper-Middle,Unemployed,Former,1,136,8.3,6.4,...,14.58,5.55,26.0,Pre-Diabetes,0,0,0,0,1,0
99996,41,1.0,Graduate,Middle,Employed,Never,3,76,8.8,6.8,...,9.02,5.97,24.4,Pre-Diabetes,0,0,0,0,0,1
99997,57,1.0,No formal,Upper-Middle,Employed,Former,4,121,9.9,5.0,...,2.57,5.21,27.6,No Diabetes,0,0,1,0,0,0
99998,47,1.0,Highschool,Lower-Middle,Retired,Never,3,52,5.9,6.7,...,9.81,5.53,26.4,Pre-Diabetes,0,0,1,0,0,0
99999,52,1.0,Postgraduate,Middle,Employed,Never,1,248,2.7,5.4,...,15.93,5.73,27.9,Pre-Diabetes,0,0,0,0,0,1

In [7]:
data['education_level'].value_counts()

education_level
Highschool      44891
Graduate        35037
Postgraduate    14972
No formal        5100
Name: count, dtype: int64

In [8]:
education_level_dummies = pd.get_dummies(data['education_level'], prefix='education_level').astype(int)
data = pd.concat([data, education_level_dummies], axis=1)
data = data.drop(columns='education_level')
data = data.rename(columns={'education_level_No formal': 'education_level_no_formal'})
data

,age,gender,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,...,diagnosed_diabetes,ethnicity_Asian,ethnicity_Black,ethnicity_Hispanic,ethnicity_Other,ethnicity_White,education_level_Graduate,education_level_Highschool,education_level_no_formal,education_level_Postgraduate
0,58,0.0,Lower-Middle,Employed,Never,0,215,5.7,7.9,7.9,...,1,1,0,0,0,0,0,1,0,0
1,48,1.0,Middle,Employed,Former,1,143,6.7,6.5,8.7,...,0,0,0,0,0,1,0,1,0,0
2,60,0.0,Middle,Unemployed,Never,1,57,6.4,10.0,8.1,...,1,0,0,1,0,0,0,1,0,0
3,74,1.0,Low,Retired,Never,0,49,3.4,6.6,5.2,...,1,0,1,0,0,0,0,1,0,0
4,46,0.0,Middle,Retired,Never,1,109,7.2,7.4,5.0,...,1,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,Upper-Middle,Unemployed,Former,1,136,8.3,6.4,4.5,...,0,0,0,0,1,0,1,0,0,0
99996,41,1.0,Middle,Employed,Never,3,76,8.8,6.8,4.8,...,0,0,0,0,0,1,1,0,0,0
99997,57,1.0,Upper-Middle,Employed,Former,4,121,9.9,5.0,6.1,...,0,0,1,0,0,0,0,0,1,0
99998,47,1.0,Lower-Middle,Retired,Never,3,52,5.9,6.7,0.5,...,0,0,1,0,0,0,0,1,0,0
99999,52,1.0,Middle,Employed,Never,1,248,2.7,5.4,5.5,...,0,0,0,0,0,1,0,0,0,1

In [9]:
data['income_level'].value_counts()

income_level
Middle          35152
Lower-Middle    25150
Upper-Middle    19866
Low             14830
High             5002
Name: count, dtype: int64

In [10]:
income_level_dummies = pd.get_dummies(data['income_level'], prefix='income_level').astype(int)
data = pd.concat([data, income_level_dummies], axis=1)
data = data.drop(columns='income_level')
data

,age,gender,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,...,ethnicity_White,education_level_Graduate,education_level_Highschool,education_level_no_formal,education_level_Postgraduate,income_level_High,income_level_Low,income_level_Lower-Middle,income_level_Middle,income_level_Upper-Middle
0,58,0.0,Employed,Never,0,215,5.7,7.9,7.9,0,...,0,0,1,0,0,0,0,1,0,0
1,48,1.0,Employed,Former,1,143,6.7,6.5,8.7,0,...,1,0,1,0,0,0,0,0,1,0
2,60,0.0,Unemployed,Never,1,57,6.4,10.0,8.1,1,...,0,0,1,0,0,0,0,0,1,0
3,74,1.0,Retired,Never,0,49,3.4,6.6,5.2,0,...,0,0,1,0,0,0,1,0,0,0
4,46,0.0,Retired,Never,1,109,7.2,7.4,5.0,0,...,1,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,Unemployed,Former,1,136,8.3,6.4,4.5,0,...,0,1,0,0,0,0,0,0,0,1
99996,41,1.0,Employed,Never,3,76,8.8,6.8,4.8,0,...,1,1,0,0,0,0,0,0,1,0
99997,57,1.0,Employed,Former,4,121,9.9,5.0,6.1,0,...,0,0,0,1,0,0,0,0,0,1
99998,47,1.0,Retired,Never,3,52,5.9,6.7,0.5,0,...,0,0,1,0,0,0,0,1,0,0
99999,52,1.0,Employed,Never,1,248,2.7,5.4,5.5,0,...,1,0,0,0,1,0,0,0,1,0

In [11]:
data['employment_status'].value_counts()

employment_status
Employed      60175
Retired       21761
Unemployed    11918
Student        6146
Name: count, dtype: int64

In [12]:
employment_status_dummies = pd.get_dummies(data['employment_status'], prefix='employment_status').astype(int)
data = pd.concat([data, employment_status_dummies], axis=1)
data = data.drop(columns='employment_status')
data

,age,gender,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,...,education_level_Postgraduate,income_level_High,income_level_Low,income_level_Lower-Middle,income_level_Middle,income_level_Upper-Middle,employment_status_Employed,employment_status_Retired,employment_status_Student,employment_status_Unemployed
0,58,0.0,Never,0,215,5.7,7.9,7.9,0,0,...,0,0,0,1,0,0,1,0,0,0
1,48,1.0,Former,1,143,6.7,6.5,8.7,0,0,...,0,0,0,0,1,0,1,0,0,0
2,60,0.0,Never,1,57,6.4,10.0,8.1,1,0,...,0,0,0,0,1,0,0,0,0,1
3,74,1.0,Never,0,49,3.4,6.6,5.2,0,0,...,0,0,1,0,0,0,0,1,0,0
4,46,0.0,Never,1,109,7.2,7.4,5.0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,Former,1,136,8.3,6.4,4.5,0,0,...,0,0,0,0,0,1,0,0,0,1
99996,41,1.0,Never,3,76,8.8,6.8,4.8,0,0,...,0,0,0,0,1,0,1,0,0,0
99997,57,1.0,Former,4,121,9.9,5.0,6.1,0,0,...,0,0,0,0,0,1,1,0,0,0
99998,47,1.0,Never,3,52,5.9,6.7,0.5,0,1,...,0,0,0,1,0,0,0,1,0,0
99999,52,1.0,Never,1,248,2.7,5.4,5.5,0,0,...,1,0,0,0,1,0,1,0,0,0

In [13]:
data['smoking_status'].value_counts()

smoking_status
Never      59813
Current    20176
Former     20011
Name: count, dtype: int64

In [14]:
smoking_status_dummies = pd.get_dummies(data['smoking_status'], prefix='smoking_status').astype(int)
data = pd.concat([data, smoking_status_dummies], axis=1)
data = data.drop(columns='smoking_status')
data

,age,gender,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,...,income_level_Lower-Middle,income_level_Middle,income_level_Upper-Middle,employment_status_Employed,employment_status_Retired,employment_status_Student,employment_status_Unemployed,smoking_status_Current,smoking_status_Former,smoking_status_Never
0,58,0.0,0,215,5.7,7.9,7.9,0,0,0,...,1,0,0,1,0,0,0,0,0,1
1,48,1.0,1,143,6.7,6.5,8.7,0,0,0,...,0,1,0,1,0,0,0,0,1,0
2,60,0.0,1,57,6.4,10.0,8.1,1,0,0,...,0,1,0,0,0,0,1,0,0,1
3,74,1.0,0,49,3.4,6.6,5.2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,46,0.0,1,109,7.2,7.4,5.0,0,0,0,...,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,1,136,8.3,6.4,4.5,0,0,0,...,0,0,1,0,0,0,1,0,1,0
99996,41,1.0,3,76,8.8,6.8,4.8,0,0,0,...,0,1,0,1,0,0,0,0,0,1
99997,57,1.0,4,121,9.9,5.0,6.1,0,0,1,...,0,0,1,1,0,0,0,0,1,0
99998,47,1.0,3,52,5.9,6.7,0.5,0,1,0,...,1,0,0,0,1,0,0,0,0,1
99999,52,1.0,1,248,2.7,5.4,5.5,0,0,0,...,0,1,0,1,0,0,0,0,0,1

In [15]:
data['diabetes_stage'].value_counts()

diabetes_stage
Type 2          59774
Pre-Diabetes    31845
No Diabetes      7981
Gestational       278
Type 1            122
Name: count, dtype: int64

In [16]:
diabetes_stage_dummies = pd.get_dummies(data['diabetes_stage'], prefix='diabetes_stage').astype(int)
data = pd.concat([data, diabetes_stage_dummies], axis=1)
data = data.drop(columns='diabetes_stage')
data

,age,gender,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,...,employment_status_Student,employment_status_Unemployed,smoking_status_Current,smoking_status_Former,smoking_status_Never,diabetes_stage_Gestational,diabetes_stage_No Diabetes,diabetes_stage_Pre-Diabetes,diabetes_stage_Type 1,diabetes_stage_Type 2
0,58,0.0,0,215,5.7,7.9,7.9,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,48,1.0,1,143,6.7,6.5,8.7,0,0,0,...,0,0,0,1,0,0,1,0,0,0
2,60,0.0,1,57,6.4,10.0,8.1,1,0,0,...,0,1,0,0,1,0,0,0,0,1
3,74,1.0,0,49,3.4,6.6,5.2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,46,0.0,1,109,7.2,7.4,5.0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,1,136,8.3,6.4,4.5,0,0,0,...,0,1,0,1,0,0,0,1,0,0
99996,41,1.0,3,76,8.8,6.8,4.8,0,0,0,...,0,0,0,0,1,0,0,1,0,0
99997,57,1.0,4,121,9.9,5.0,6.1,0,0,1,...,0,0,0,1,0,0,1,0,0,0
99998,47,1.0,3,52,5.9,6.7,0.5,0,1,0,...,0,0,0,0,1,0,0,1,0,0
99999,52,1.0,1,248,2.7,5.4,5.5,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [17]:
data = data.rename(columns={'diagnosed_diabetes': 'target'})
data.columns = data.columns.map(lambda x: x.strip().lower().replace(' ', '_').replace('-', '_'))
data

,age,gender,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,family_history_diabetes,hypertension_history,cardiovascular_history,...,employment_status_student,employment_status_unemployed,smoking_status_current,smoking_status_former,smoking_status_never,diabetes_stage_gestational,diabetes_stage_no_diabetes,diabetes_stage_pre_diabetes,diabetes_stage_type_1,diabetes_stage_type_2
0,58,0.0,0,215,5.7,7.9,7.9,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,48,1.0,1,143,6.7,6.5,8.7,0,0,0,...,0,0,0,1,0,0,1,0,0,0
2,60,0.0,1,57,6.4,10.0,8.1,1,0,0,...,0,1,0,0,1,0,0,0,0,1
3,74,1.0,0,49,3.4,6.6,5.2,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4,46,0.0,1,109,7.2,7.4,5.0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,46,0.0,1,136,8.3,6.4,4.5,0,0,0,...,0,1,0,1,0,0,0,1,0,0
99996,41,1.0,3,76,8.8,6.8,4.8,0,0,0,...,0,0,0,0,1,0,0,1,0,0
99997,57,1.0,4,121,9.9,5.0,6.1,0,0,1,...,0,0,0,1,0,0,1,0,0,0
99998,47,1.0,3,52,5.9,6.7,0.5,0,1,0,...,0,0,0,0,1,0,0,1,0,0
99999,52,1.0,1,248,2.7,5.4,5.5,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [18]:
# dataset = data
# dataset.to_csv('preprocessed_data/dataset.csv', index=False)